name: CI
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install dvc
        pip install mlflow
    
    - name: Run DVC pipeline
      run: dvc repro
    
    - name: Create MLFlow directory
      run: mkdir -p mlruns
    
    - name: Run MLflow tracking
      run: python python-pipeline.py
