name: CI
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run DVC pipeline
        run: |
          pip install dvc
          dvc repro
      - name: Run MLflow tracking
        run: |
          pip install mlflow
          mkdir -p mlruns  # Create MLflow directory
          python pipeline.py
